# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/CodeSVN/urban/trunk/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/CodeSVN/urban/trunk/code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/CodeSVN/urban/trunk/code/CMakeFiles /home/david/CodeSVN/urban/trunk/code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/CodeSVN/urban/trunk/code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Urban_simplification

# Build rule for target.
Urban_simplification: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Urban_simplification
.PHONY : Urban_simplification

# fast build rule for target.
Urban_simplification/fast:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/build
.PHONY : Urban_simplification/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

src/benchmark/benchmark.o: src/benchmark/benchmark.cpp.o
.PHONY : src/benchmark/benchmark.o

# target to build an object file
src/benchmark/benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/benchmark/benchmark.cpp.o
.PHONY : src/benchmark/benchmark.cpp.o

src/benchmark/benchmark.i: src/benchmark/benchmark.cpp.i
.PHONY : src/benchmark/benchmark.i

# target to preprocess a source file
src/benchmark/benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/benchmark/benchmark.cpp.i
.PHONY : src/benchmark/benchmark.cpp.i

src/benchmark/benchmark.s: src/benchmark/benchmark.cpp.s
.PHONY : src/benchmark/benchmark.s

# target to generate assembly for a file
src/benchmark/benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/benchmark/benchmark.cpp.s
.PHONY : src/benchmark/benchmark.cpp.s

src/contraction/CGAL_contractor.o: src/contraction/CGAL_contractor.cpp.o
.PHONY : src/contraction/CGAL_contractor.o

# target to build an object file
src/contraction/CGAL_contractor.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/contraction/CGAL_contractor.cpp.o
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/contraction/CGAL_contractor.cpp.o
.PHONY : src/contraction/CGAL_contractor.cpp.o

src/contraction/CGAL_contractor.i: src/contraction/CGAL_contractor.cpp.i
.PHONY : src/contraction/CGAL_contractor.i

# target to preprocess a source file
src/contraction/CGAL_contractor.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/contraction/CGAL_contractor.cpp.i
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/contraction/CGAL_contractor.cpp.i
.PHONY : src/contraction/CGAL_contractor.cpp.i

src/contraction/CGAL_contractor.s: src/contraction/CGAL_contractor.cpp.s
.PHONY : src/contraction/CGAL_contractor.s

# target to generate assembly for a file
src/contraction/CGAL_contractor.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/contraction/CGAL_contractor.cpp.s
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/contraction/CGAL_contractor.cpp.s
.PHONY : src/contraction/CGAL_contractor.cpp.s

src/interface/MainWindow.o: src/interface/MainWindow.cpp.o
.PHONY : src/interface/MainWindow.o

# target to build an object file
src/interface/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/MainWindow.cpp.o
.PHONY : src/interface/MainWindow.cpp.o

src/interface/MainWindow.i: src/interface/MainWindow.cpp.i
.PHONY : src/interface/MainWindow.i

# target to preprocess a source file
src/interface/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/MainWindow.cpp.i
.PHONY : src/interface/MainWindow.cpp.i

src/interface/MainWindow.s: src/interface/MainWindow.cpp.s
.PHONY : src/interface/MainWindow.s

# target to generate assembly for a file
src/interface/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/MainWindow.cpp.s
.PHONY : src/interface/MainWindow.cpp.s

src/interface/Menu_detect_primitive.o: src/interface/Menu_detect_primitive.cpp.o
.PHONY : src/interface/Menu_detect_primitive.o

# target to build an object file
src/interface/Menu_detect_primitive.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_detect_primitive.cpp.o
.PHONY : src/interface/Menu_detect_primitive.cpp.o

src/interface/Menu_detect_primitive.i: src/interface/Menu_detect_primitive.cpp.i
.PHONY : src/interface/Menu_detect_primitive.i

# target to preprocess a source file
src/interface/Menu_detect_primitive.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_detect_primitive.cpp.i
.PHONY : src/interface/Menu_detect_primitive.cpp.i

src/interface/Menu_detect_primitive.s: src/interface/Menu_detect_primitive.cpp.s
.PHONY : src/interface/Menu_detect_primitive.s

# target to generate assembly for a file
src/interface/Menu_detect_primitive.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_detect_primitive.cpp.s
.PHONY : src/interface/Menu_detect_primitive.cpp.s

src/interface/Menu_edge_collapse.o: src/interface/Menu_edge_collapse.cpp.o
.PHONY : src/interface/Menu_edge_collapse.o

# target to build an object file
src/interface/Menu_edge_collapse.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_edge_collapse.cpp.o
.PHONY : src/interface/Menu_edge_collapse.cpp.o

src/interface/Menu_edge_collapse.i: src/interface/Menu_edge_collapse.cpp.i
.PHONY : src/interface/Menu_edge_collapse.i

# target to preprocess a source file
src/interface/Menu_edge_collapse.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_edge_collapse.cpp.i
.PHONY : src/interface/Menu_edge_collapse.cpp.i

src/interface/Menu_edge_collapse.s: src/interface/Menu_edge_collapse.cpp.s
.PHONY : src/interface/Menu_edge_collapse.s

# target to generate assembly for a file
src/interface/Menu_edge_collapse.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Menu_edge_collapse.cpp.s
.PHONY : src/interface/Menu_edge_collapse.cpp.s

src/interface/Viewer.o: src/interface/Viewer.cpp.o
.PHONY : src/interface/Viewer.o

# target to build an object file
src/interface/Viewer.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer.cpp.o
.PHONY : src/interface/Viewer.cpp.o

src/interface/Viewer.i: src/interface/Viewer.cpp.i
.PHONY : src/interface/Viewer.i

# target to preprocess a source file
src/interface/Viewer.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer.cpp.i
.PHONY : src/interface/Viewer.cpp.i

src/interface/Viewer.s: src/interface/Viewer.cpp.s
.PHONY : src/interface/Viewer.s

# target to generate assembly for a file
src/interface/Viewer.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer.cpp.s
.PHONY : src/interface/Viewer.cpp.s

src/interface/Viewer_instructor.o: src/interface/Viewer_instructor.cpp.o
.PHONY : src/interface/Viewer_instructor.o

# target to build an object file
src/interface/Viewer_instructor.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer_instructor.cpp.o
.PHONY : src/interface/Viewer_instructor.cpp.o

src/interface/Viewer_instructor.i: src/interface/Viewer_instructor.cpp.i
.PHONY : src/interface/Viewer_instructor.i

# target to preprocess a source file
src/interface/Viewer_instructor.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer_instructor.cpp.i
.PHONY : src/interface/Viewer_instructor.cpp.i

src/interface/Viewer_instructor.s: src/interface/Viewer_instructor.cpp.s
.PHONY : src/interface/Viewer_instructor.s

# target to generate assembly for a file
src/interface/Viewer_instructor.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/interface/Viewer_instructor.cpp.s
.PHONY : src/interface/Viewer_instructor.cpp.s

src/semantic/CloudSegmentation.o: src/semantic/CloudSegmentation.cpp.o
.PHONY : src/semantic/CloudSegmentation.o

# target to build an object file
src/semantic/CloudSegmentation.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/CloudSegmentation.cpp.o
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/CloudSegmentation.cpp.o
.PHONY : src/semantic/CloudSegmentation.cpp.o

src/semantic/CloudSegmentation.i: src/semantic/CloudSegmentation.cpp.i
.PHONY : src/semantic/CloudSegmentation.i

# target to preprocess a source file
src/semantic/CloudSegmentation.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/CloudSegmentation.cpp.i
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/CloudSegmentation.cpp.i
.PHONY : src/semantic/CloudSegmentation.cpp.i

src/semantic/CloudSegmentation.s: src/semantic/CloudSegmentation.cpp.s
.PHONY : src/semantic/CloudSegmentation.s

# target to generate assembly for a file
src/semantic/CloudSegmentation.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/CloudSegmentation.cpp.s
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/CloudSegmentation.cpp.s
.PHONY : src/semantic/CloudSegmentation.cpp.s

src/semantic/Enriched_mesh.o: src/semantic/Enriched_mesh.cpp.o
.PHONY : src/semantic/Enriched_mesh.o

# target to build an object file
src/semantic/Enriched_mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/Enriched_mesh.cpp.o
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/Enriched_mesh.cpp.o
.PHONY : src/semantic/Enriched_mesh.cpp.o

src/semantic/Enriched_mesh.i: src/semantic/Enriched_mesh.cpp.i
.PHONY : src/semantic/Enriched_mesh.i

# target to preprocess a source file
src/semantic/Enriched_mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/Enriched_mesh.cpp.i
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/Enriched_mesh.cpp.i
.PHONY : src/semantic/Enriched_mesh.cpp.i

src/semantic/Enriched_mesh.s: src/semantic/Enriched_mesh.cpp.s
.PHONY : src/semantic/Enriched_mesh.s

# target to generate assembly for a file
src/semantic/Enriched_mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/src/semantic/Enriched_mesh.cpp.s
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/semantic/Enriched_mesh.cpp.s
.PHONY : src/semantic/Enriched_mesh.cpp.s

test/demo_contraction.o: test/demo_contraction.cpp.o
.PHONY : test/demo_contraction.o

# target to build an object file
test/demo_contraction.cpp.o:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/test/demo_contraction.cpp.o
.PHONY : test/demo_contraction.cpp.o

test/demo_contraction.i: test/demo_contraction.cpp.i
.PHONY : test/demo_contraction.i

# target to preprocess a source file
test/demo_contraction.cpp.i:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/test/demo_contraction.cpp.i
.PHONY : test/demo_contraction.cpp.i

test/demo_contraction.s: test/demo_contraction.cpp.s
.PHONY : test/demo_contraction.s

# target to generate assembly for a file
test/demo_contraction.cpp.s:
	$(MAKE) -f CMakeFiles/Urban_simplification.dir/build.make CMakeFiles/Urban_simplification.dir/test/demo_contraction.cpp.s
.PHONY : test/demo_contraction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Urban_simplification"
	@echo "... benchmark"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/benchmark/benchmark.o"
	@echo "... src/benchmark/benchmark.i"
	@echo "... src/benchmark/benchmark.s"
	@echo "... src/contraction/CGAL_contractor.o"
	@echo "... src/contraction/CGAL_contractor.i"
	@echo "... src/contraction/CGAL_contractor.s"
	@echo "... src/interface/MainWindow.o"
	@echo "... src/interface/MainWindow.i"
	@echo "... src/interface/MainWindow.s"
	@echo "... src/interface/Menu_detect_primitive.o"
	@echo "... src/interface/Menu_detect_primitive.i"
	@echo "... src/interface/Menu_detect_primitive.s"
	@echo "... src/interface/Menu_edge_collapse.o"
	@echo "... src/interface/Menu_edge_collapse.i"
	@echo "... src/interface/Menu_edge_collapse.s"
	@echo "... src/interface/Viewer.o"
	@echo "... src/interface/Viewer.i"
	@echo "... src/interface/Viewer.s"
	@echo "... src/interface/Viewer_instructor.o"
	@echo "... src/interface/Viewer_instructor.i"
	@echo "... src/interface/Viewer_instructor.s"
	@echo "... src/semantic/CloudSegmentation.o"
	@echo "... src/semantic/CloudSegmentation.i"
	@echo "... src/semantic/CloudSegmentation.s"
	@echo "... src/semantic/Enriched_mesh.o"
	@echo "... src/semantic/Enriched_mesh.i"
	@echo "... src/semantic/Enriched_mesh.s"
	@echo "... test/demo_contraction.o"
	@echo "... test/demo_contraction.i"
	@echo "... test/demo_contraction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

